### ISSUE TITLE
Generated images not being copied to compiled _site

### ISSUE THREAD

**Issue by sawyerh** [wildlyinaccurate/jekyll-responsive-image#38]
Hey there. Thanks for your work on this, it's looking very promising!

I'm running into a pretty big blocker and it's possible I'm just missing something. Here's what I'm experiencing when I try using the `responsive_image` tag and run `jekyll build`:

1. An output directory and the generated image file is placed in the root of my project folder. I.e `my-project/assets/resized/image-800x512.jpg`
2. The output directory is placed in the compiled `_site` directory, however the generate image file is not. For example: `my-project/_site/assets/resized/` is created, however `my-project/_site/assets/resized/image-800x512.jpg` is not created. This results in a 404 if the image is referenced in the template.

![image](https://cloud.githubusercontent.com/assets/371943/19334602/01def518-90cb-11e6-84ee-e976193187fd.png)

Here's the output in terminal:

```bash
$ bundle exec jekyll b
Configuration file: /Users/sawyer/Sites/example.com/_config.yml
            Source: /Users/sawyer/Sites/example.com
       Destination: /Users/sawyer/Sites/example.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Creating output directory assets/resized
Generating assets/resized/images-800x512.jpg
                    done in 0.334 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

What I'd expect to happen is: The root directory of my project where my source files are is left alone, and `jekyll-responsive-image` would only create the `resized` directory and generated images in `_site` when the site is served or built.

Here's what my `_config.yml` looks like:

```yaml
responsive_image:
  template: _includes/slider-image.html
  sizes:
    - width: 800
      quality: 60
```

Is this a bug or is there a different way you expect the site to be built? 

Thanks again!

**Comment by wildlyinaccurate** [comment]
Hey, thanks for the detailed report! So you mentioned two things:

1. Resized images are being generated in your source directory. This is the expected behaviour, and there's currently no way to get around it. The intention is that if your site is checked into version control, you would check in the resized images so that they don't need to be generated on every build.
2. Resized images aren't being copied to your destination directory. This is definitely a bug. There's [a bunch of code](https://github.com/wildlyinaccurate/jekyll-responsive-image/blob/0b01bc0f05c5575050645a064b2589db97a453ce/lib/jekyll/responsive_image/resize_handler.rb#L32-L35) which specifically makes sure the images _are_ copied to the destination directory, but it looks like that's not working for you.

Could you try installing version `1.0.0.pre4` of the gem, and let me know if that makes a difference? If not, would you mind providing a few extra details:

 * Your full Jekyll config
 * An example of where the `{% responsive_image %}` tag is being used
 * The path to the original `image.jpg`

Thanks!

**Comment by sawyerh** [comment]
> The intention is that if your site is checked into version control, you would check in the resized images so that they don't need to be generated on every build.

Ah ok. I see what you're saying, but may need to loop back to this in a separate ticket after some more debugging :)

> Could you try installing version 1.0.0.pre4 of the gem, and let me know if that makes a difference? 

This solved the problem and resized images now get copied to the destination directory 👍
