### ISSUE TITLE
Error when running jekyll

### ISSUE THREAD

**Issue by niij** [wildlyinaccurate/jekyll-responsive-image#58]
I am running Linux.  I have installed jekyll-responsive-image and rmagick.  When I go to run ```jekyll serve``` I get this error:

```
Configuration file: /home/myusername/project/_config.yml
Configuration file: /home/myusername/project/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-responsive-image or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'libMagickCore-6.Q16.so.4: cannot open shared object file: No such file or directory - /home/myusername/.rvm/gems/ruby-2.4.0/gems/rmagick-2.16.0/lib/RMagick2.so' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
jekyll 3.4.3 | Error:  jekyll-responsive-image
```

I tried to do a pristine reinstall of both gems, as well as reinstall rmagick through brew, but I still get this error. Any clues how I can get this plugin working?

**Comment by wildlyinaccurate** [comment]
Hey, apologies for the slow reply. From your comment on #20, I assume you got this working in the end?

**Comment by driehuis** [comment]
The `rmagick` gem appears not to have been installed completely at the time of the first comment.

For the benefit of those Googling the error message and arriving at this issue, an error message quite like that is generated if one uses bundler for jekyll and neglects to add the plugin to the Gemfile (as I did, stoopidly). If I've got some time left after draining my pond I'll see if I can come up with some suggested wording to address this issue in the `README.md` (which is excellent, by the way; I hit the ground running, only to forget I religiously apply `bundler` all over :-)

Instead of referring to `libMagickCore-6.Q16.so.4`, my error referred to `cannot load such file -- jekyll-responsive-image`.
