### ISSUE TITLE
take advantage of change_geometry

### ISSUE THREAD

**Issue by jericbryledy** [wildlyinaccurate/jekyll-responsive-image#64]
Only allowing `width` to be specified is a bit restrictive. I sometimes need to scale base on the height.
I think this library should take advantage of Magick's geometry string with `change_geometry`.
I can make this commit, just give me a go signal.

**Comment by wildlyinaccurate** [comment]
Hey, thanks for the suggestion!

I'm hesitant to implement height-based resizing because --as far as I'm aware-- all of the responsive image specs are based on width. The purpose of this plugin is to reduce some of the manual resizing required for implementing responsive images, rather than a general-purpose image resizer (although I admit the lines are very blurry now with the `extra_images` option).

Could you sketch out a use case for me, and maybe explain how this would look in the Jekyll config?

**Comment by wildlyinaccurate** [comment]
This is _kind of_ related to #29.

**Comment by jericbryledy** [comment]
I use height-based resizing on carousel images like in https://www.jericdy.com/games/

**Comment by jericbryledy** [comment]
Now that I've think about it. I shouldn't be using this plugin as a thumbnail generator...
