### ISSUE TITLE
Removing an image leaves stale content in _site/assets/resized/

### ISSUE THREAD

**Issue by pwmarcz** [wildlyinaccurate/jekyll-responsive-image#82]
To reproduce: 
1. create an image file, use it in `{% responsive_image %}`
2. `jekyll build`
3. remove the image file and `{% responsive_image %}` block
3. `jekyll build` again

The resized file remains in `_site/assets/resized/`. I would expect it to be deleted, because that is what `jekyll build` does with all the other stale files in `_site/`.

**Comment by wildlyinaccurate** [comment]
Unfortunately there's no way for the plugin to know whether it should delete an image, simply because it's possible for you (or another plugin) to put images into your "resized" directory.

If you have a separate "resized" directory that is _only_ used by this plugin, then I would deleting it before each build to start with a clean slate. Just be aware that this will increase your builds times.
